/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tdf_natives_Crypto */

#ifndef _Included_org_tdf_natives_Crypto
#define _Included_org_tdf_natives_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tdf_natives_Crypto
 * Method:    sm3
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tdf_natives_Crypto_sm3
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_tdf_natives_Crypto
 * Method:    sm2PkFromSk
 * Signature: ([BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tdf_natives_Crypto_sm2PkFromSk
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     org_tdf_natives_Crypto
 * Method:    sm2Verify
 * Signature: (J[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tdf_natives_Crypto_sm2Verify
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_tdf_natives_Crypto
 * Method:    sm2Sign
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tdf_natives_Crypto_sm2Sign
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
