package org.tdf.sunflower.consensus.vrf.core;

public enum ProofValidationResult {
    OK, PROOF_NOT_EXISTING, PROOF_AND_IDENTIFIER_NOT_MATCH, PRIORITY_NOT_QUALIFIED, NOT_BEST_BLOCK, NO_BEST_IDENTIFIER, PROOF_AND_BEST_IDENTIFIER_NOT_MATCH, LOW_WEIGHTS;
}
