# use SPRING_CONFIG_LOCATION environment to locate your custom spring config
# for example: SPRING_CONFIG_LOCATION=classpath:\application.yml,some-path\custom-config.yml
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/your-data-base' # SPRING_DATASOURCE_URL
    username: 'username'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: create-drop # create, update
    show-sql: false # enable jpa sql logs



# sunflower configurations
sunflower:
  consensus:
    name: 'none'
    genesis: 'genesis/poa.jsonc'
    block-interval: '30'
    enable-mining: 'true'
    miner-coin-base: '87b8f0b097b48b282a5c661babc8096e141bd9fb'
    
    # VRF configs
 # consensus:
 #   name: 'vrf'
 #   genesis: 'genesis/vrf.json'
 #   block-interval: '3'
 #   enable-mining: 'false'
 #   miner-coin-base: '1JWhUiZCWps56uZckAvzxy2ex6VGhrMXdD'
    # VRF keystore path of pk & sk. Relative path to /home/$USER/.sunflower
#    vrf-data-dir: vrfdata

  p2p:
    name: 'websocket' # choose p2p protocol, gRPC is default optional: websocket
    # name: 'websocket'
    max-peers: '16' # maximum peers
    address: 'node://localhost:9999'
    enable-discovery: 'true'
    enable-message-log: 'true' # set false to disable verbose log
    bootstraps: # bootstraps nodes
      - 'node://localhost:9998'
    trusted: # trusted nodes
      - 'node://localhost:9999'

  message-queue:
    name: 'socketIO'
    port: '8081'
    enable-message-log: 'true' # set false to disable verbose log

  # command line interface
  console:
    token-file: 'sunflower.ipr' # location to write token file, json format {token: '', port: 8888}
    port: '8082'
    disabled: 'false'

  database:
    # Key value data source values: [rocksdb/leveldb/memory]
    name: 'rocksdb'
    directory: 'database/rocksdb'
    max-open-files: '512' # defines a number of opened files by db instance

  # 密码算法，包含对称加密，非对称加密和哈希计算
  crpto:
    hash: 'sm3' # keccak256, keccak512
    ec: 'sm2' # ed25519
    ae: 'sm4' #

server:
  port: '8080'

logging:
  level:
    org.hibernate:
      SQL: 'DEBUG'
      type.descriptor.sql.BasicBinder: 'TRACE'
    org.springframework.jdbc.core:
      JdbcTemplate: 'DEBUG'
      StatementCreatorUtils: 'TRACE'
