# use SPRING_CONFIG_LOCATION environment to locate your custom spring config
# for example: SPRING_CONFIG_LOCATION=classpath:\application.yml,some-path\custom-config.yml
spring:
  datasource:
    url: 'jdbc:h2:mem:testdb' # SPRING_DATASOURCE_URL
    username: 'username'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: create-drop # create, update
    show-sql: false # enable jpa sql logs


# sunflower configurations
sunflower:
  # enable assert in development
  # call org.tdf.sunflower.Start.devAssert
  assert: 'false'
  validate: 'false'
  consensus:
    name: 'poa'
    genesis: 'genesis/poa.jsonc'
    block-interval: '30'
    enable-mining: 'true'
    miner-coin-base: '87b8f0b097b48b282a5c661babc8096e141bd9fb'
    allow-empty-block: 'true'
    # maximum transactions in a block
    max-body-size: '2048'

    #pos
#  consensus:
#    name: 'pos'
#    genesis: 'genesis/pos.jsonc'
#    block-interval: '10'
#    enable-mining: 'true'
#    miner-coin-base: '87b8f0b097b48b282a5c661babc8096e141bd9fb'
#    allow-empty-block: 'true'
#    max-body-size: '2048'

    
    # VRF configs
 # consensus:
 #   name: 'vrf'
 #   genesis: 'genesis/vrf.json'
 #   block-interval: '3'
 #   enable-mining: 'false'
 #   miner-coin-base: '1JWhUiZCWps56uZckAvzxy2ex6VGhrMXdD'
    # VRF keystore path of pk & sk. Relative path to /home/$USER/.sunflower
#    vrf-data-dir: vrfdata

  p2p:
    name: 'websocket' # choose p2p protocol, gRPC is default optional: websocket
    # name: 'websocket'
    max-peers: '16' # maximum peers
    address: 'node://localhost:9999'
    enable-discovery: 'true'
    # enable-message-log: 'true' # set false to disable verbose log
    # bootstraps:
      # - 'node://localhost:9998'
    # trusted: # trusted nodes
      # - 'node://localhost:9999'

    # if white list is not empty, only nodes in white list are allowed to be connected
    # white-list:
      # - ffff

    # the node in blocked list are not allowed to be connected
    # blocked-list:

    # if private-key is not pre-defined, node will generate private key
    # private-key:

    # persist peers to file database.directory/peers.json
    persist: true

    # lookup peers every 15 seconds
    discover-rate: 15

    # maximum packae
    max-packet-size: 2097152
    cache-expired-after: 300

  transaction-pool:
    expired-in: '300'
    lock-timeout: '1'
  sync:
  #status rate(seconds)
    heart-rate: 5
    block-write-rate: 1
    max-pending-blocks: 2048
    max-blocks-transfer: 1024
    # drop old header, transaction and states
    prune-hash: ''
    # enable fast sync process
    fast-sync-hash: ''
    fast-sync-height: '0'
    max-accounts-transfer: 512
    lock-timeout: 1

    # limit message rates
    rate-limits:
      status: '16'
      get-blocks: '16'

  message-queue:
    name: 'socketIO'
    port: '8081'
    host: '0.0.0.0'
    origin: ''
    #enable-message-log: 'true' # set false to disable verbose log

  # command line interface
  #console:
    #token-file: 'sunflower.ipr' # location to write token file, json format {token: '', port: 8888}
    #port: '8082'
    #disabled: 'false'

  database:
    # Key value data source values: [rocksdb/leveldb/memory]
    name: 'leveldb'
    directory: 'database/rocksdb'
    max-open-files: '512' # defines a number of opened files by db instance
    block-store: 'rdbms' # optional: kv

  # 密码算法，包含对称加密，非对称加密和哈希计算
  crypto:
    hash: 'sm3' # keccak256, keccak512
    ec: 'sm2' # ed25519
    ae: 'sm4' # 对称加密方法


  vm:
    # gas limit for contract execution, any vm code or host function execution consumes one gas
    gas-limit: '4294967296'

  web:
    disabled: false
    password: password

  # constants for cache
  cache:
    # cache size for state trie
    trie: '32'
    # cache size for avoid message flood
    p2p:
      transaction: '128'
      # cache size for avoid message flood
      proposal: '128'


server:
  port: '8080'

#logging:
  #level:
    #org.hibernate:
      #SQL: 'DEBUG'
      #type.descriptor.sql.BasicBinder: 'TRACE'
    #org.springframework.jdbc.core:
      #JdbcTemplate: 'DEBUG'
      #StatementCreatorUtils: 'TRACE'
