// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.wisdom.consortium.proto;

public final class Consortium {
  private Consortium() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lookup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lookup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Peers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Peers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nothing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nothing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020consortium.proto\032\037google/protobuf/time" +
      "stamp.proto\"\240\001\n\007Message\022\023\n\004code\030\001 \001(\0162\005." +
      "Code\022.\n\ncreated_at\030\002 \001(\0132\032.google.protob" +
      "uf.Timestamp\022\023\n\013remote_peer\030\003 \001(\t\022\013\n\003ttl" +
      "\030\004 \001(\004\022\r\n\005nonce\030\005 \001(\004\022\021\n\tsignature\030\006 \001(\014" +
      "\022\014\n\004body\030\007 \001(\014\"\006\n\004Ping\"\006\n\004Pong\"\010\n\006Lookup" +
      "\"\026\n\005Peers\022\r\n\005peers\030\001 \003(\t\"\t\n\007Nothing*L\n\004C" +
      "ode\022\013\n\007NOTHING\020\000\022\010\n\004PING\020\001\022\010\n\004PONG\020\002\022\013\n\007" +
      "LOOK_UP\020\003\022\t\n\005PEERS\020\004\022\013\n\007ANOTHER\020\0052*\n\005Ent" +
      "ry\022!\n\005Entry\022\010.Message\032\010.Message\"\000(\0010\001B\037\n" +
      "\033org.wisdom.consortium.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Code", "CreatedAt", "RemotePeer", "Ttl", "Nonce", "Signature", "Body", });
    internal_static_Ping_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ping_descriptor,
        new java.lang.String[] { });
    internal_static_Pong_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pong_descriptor,
        new java.lang.String[] { });
    internal_static_Lookup_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Lookup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lookup_descriptor,
        new java.lang.String[] { });
    internal_static_Peers_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Peers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Peers_descriptor,
        new java.lang.String[] { "Peers", });
    internal_static_Nothing_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Nothing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nothing_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
