// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.wisdom.consortium.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * protocol header
   * </pre>
   *
   * <code>.Code code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   * protocol header
   * </pre>
   *
   * <code>.Code code = 1;</code>
   * @return The code.
   */
  org.wisdom.consortium.proto.Code getCode();

  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>string remote_peer = 3;</code>
   * @return The remotePeer.
   */
  java.lang.String getRemotePeer();
  /**
   * <code>string remote_peer = 3;</code>
   * @return The bytes for remotePeer.
   */
  com.google.protobuf.ByteString
      getRemotePeerBytes();

  /**
   * <pre>
   * avoid flood attack
   * </pre>
   *
   * <code>uint64 ttl = 4;</code>
   * @return The ttl.
   */
  long getTtl();

  /**
   * <pre>
   * avoid collision
   * </pre>
   *
   * <code>uint64 nonce = 5;</code>
   * @return The nonce.
   */
  long getNonce();

  /**
   * <code>bytes signature = 6;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <pre>
   * protocol body
   * </pre>
   *
   * <code>bytes body = 7;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
