// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.wisdom.consortium.proto;

public interface NothingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Nothing)
    com.google.protobuf.MessageOrBuilder {
}
