// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.wisdom.consortium.proto;

public interface PeersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Peers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string peers = 1;</code>
   * @return A list containing the peers.
   */
  java.util.List<java.lang.String>
      getPeersList();
  /**
   * <code>repeated string peers = 1;</code>
   * @return The count of peers.
   */
  int getPeersCount();
  /**
   * <code>repeated string peers = 1;</code>
   * @param index The index of the element to return.
   * @return The peers at the given index.
   */
  java.lang.String getPeers(int index);
  /**
   * <code>repeated string peers = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the peers at the given index.
   */
  com.google.protobuf.ByteString
      getPeersBytes(int index);
}
