// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.wisdom.consortium.proto;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Pong)
    com.google.protobuf.MessageOrBuilder {
}
