// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

public interface DisconnectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Disconnect)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reason = 1;</code>
     *
     * @return The reason.
     */
    java.lang.String getReason();

    /**
     * <code>string reason = 1;</code>
     *
     * @return The bytes for reason.
     */
    com.google.protobuf.ByteString
    getReasonBytes();
}
