// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

public interface LookupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lookup)
    com.google.protobuf.MessageOrBuilder {
}
