// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

/**
 * Protobuf type {@code MultiPart}
 */
public final class MultiPart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MultiPart)
    MultiPartOrBuilder {
    public static final int HASH_FIELD_NUMBER = 1;
    public static final int PACKET_FIELD_NUMBER = 2;
    public static final int INDEX_FIELD_NUMBER = 3;
    public static final int TOTAL_FIELD_NUMBER = 4;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:MultiPart)
    private static final org.tdf.sunflower.proto.MultiPart DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<MultiPart>
        PARSER = new com.google.protobuf.AbstractParser<MultiPart>() {
        @java.lang.Override
        public MultiPart parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new MultiPart(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new org.tdf.sunflower.proto.MultiPart();
    }

    private com.google.protobuf.ByteString hash_;
    private com.google.protobuf.ByteString packet_;
    private int index_;
    private int total_;
    private byte memoizedIsInitialized = -1;

    // Use MultiPart.newBuilder() to construct.
    private MultiPart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private MultiPart() {
        hash_ = com.google.protobuf.ByteString.EMPTY;
        packet_ = com.google.protobuf.ByteString.EMPTY;
    }

    private MultiPart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {

                        hash_ = input.readBytes();
                        break;
                    }
                    case 18: {

                        packet_ = input.readBytes();
                        break;
                    }
                    case 24: {

                        index_ = input.readUInt32();
                        break;
                    }
                    case 32: {

                        total_ = input.readUInt32();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.tdf.sunflower.proto.Sunflower.internal_static_MultiPart_descriptor;
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.MultiPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.MultiPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.MultiPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.tdf.sunflower.proto.MultiPart prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.tdf.sunflower.proto.MultiPart getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<MultiPart> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
        return new MultiPart();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.tdf.sunflower.proto.Sunflower.internal_static_MultiPart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdf.sunflower.proto.MultiPart.class, org.tdf.sunflower.proto.MultiPart.Builder.class);
    }

    /**
     * <code>bytes hash = 1;</code>
     *
     * @return The hash.
     */
    public com.google.protobuf.ByteString getHash() {
        return hash_;
    }

    /**
     * <code>bytes packet = 2;</code>
     *
     * @return The packet.
     */
    public com.google.protobuf.ByteString getPacket() {
        return packet_;
    }

    /**
     * <code>uint32 index = 3;</code>
     *
     * @return The index.
     */
    public int getIndex() {
        return index_;
    }

    /**
     * <code>uint32 total = 4;</code>
     *
     * @return The total.
     */
    public int getTotal() {
        return total_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!hash_.isEmpty()) {
            output.writeBytes(1, hash_);
        }
        if (!packet_.isEmpty()) {
            output.writeBytes(2, packet_);
        }
        if (index_ != 0) {
            output.writeUInt32(3, index_);
        }
        if (total_ != 0) {
            output.writeUInt32(4, total_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!hash_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, hash_);
        }
        if (!packet_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, packet_);
        }
        if (index_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(3, index_);
        }
        if (total_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(4, total_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.tdf.sunflower.proto.MultiPart)) {
            return super.equals(obj);
        }
        org.tdf.sunflower.proto.MultiPart other = (org.tdf.sunflower.proto.MultiPart) obj;

        if (!getHash()
            .equals(other.getHash())) return false;
        if (!getPacket()
            .equals(other.getPacket())) return false;
        if (getIndex()
            != other.getIndex()) return false;
        if (getTotal()
            != other.getTotal()) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash().hashCode();
        hash = (37 * hash) + PACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPacket().hashCode();
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex();
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultiPart> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.tdf.sunflower.proto.MultiPart getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code MultiPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MultiPart)
        org.tdf.sunflower.proto.MultiPartOrBuilder {
        private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.ByteString packet_ = com.google.protobuf.ByteString.EMPTY;
        private int index_;
        private int total_;

        // Construct using org.tdf.sunflower.proto.MultiPart.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_MultiPart_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_MultiPart_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    org.tdf.sunflower.proto.MultiPart.class, org.tdf.sunflower.proto.MultiPart.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            hash_ = com.google.protobuf.ByteString.EMPTY;

            packet_ = com.google.protobuf.ByteString.EMPTY;

            index_ = 0;

            total_ = 0;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_MultiPart_descriptor;
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.MultiPart getDefaultInstanceForType() {
            return org.tdf.sunflower.proto.MultiPart.getDefaultInstance();
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.MultiPart build() {
            org.tdf.sunflower.proto.MultiPart result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.MultiPart buildPartial() {
            org.tdf.sunflower.proto.MultiPart result = new org.tdf.sunflower.proto.MultiPart(this);
            result.hash_ = hash_;
            result.packet_ = packet_;
            result.index_ = index_;
            result.total_ = total_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.tdf.sunflower.proto.MultiPart) {
                return mergeFrom((org.tdf.sunflower.proto.MultiPart) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.tdf.sunflower.proto.MultiPart other) {
            if (other == org.tdf.sunflower.proto.MultiPart.getDefaultInstance()) return this;
            if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
                setHash(other.getHash());
            }
            if (other.getPacket() != com.google.protobuf.ByteString.EMPTY) {
                setPacket(other.getPacket());
            }
            if (other.getIndex() != 0) {
                setIndex(other.getIndex());
            }
            if (other.getTotal() != 0) {
                setTotal(other.getTotal());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            org.tdf.sunflower.proto.MultiPart parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.tdf.sunflower.proto.MultiPart) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>bytes hash = 1;</code>
         *
         * @return The hash.
         */
        public com.google.protobuf.ByteString getHash() {
            return hash_;
        }

        /**
         * <code>bytes hash = 1;</code>
         *
         * @param value The hash to set.
         * @return This builder for chaining.
         */
        public Builder setHash(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            hash_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes hash = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearHash() {

            hash_ = getDefaultInstance().getHash();
            onChanged();
            return this;
        }

        /**
         * <code>bytes packet = 2;</code>
         *
         * @return The packet.
         */
        public com.google.protobuf.ByteString getPacket() {
            return packet_;
        }

        /**
         * <code>bytes packet = 2;</code>
         *
         * @param value The packet to set.
         * @return This builder for chaining.
         */
        public Builder setPacket(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            packet_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes packet = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPacket() {

            packet_ = getDefaultInstance().getPacket();
            onChanged();
            return this;
        }

        /**
         * <code>uint32 index = 3;</code>
         *
         * @return The index.
         */
        public int getIndex() {
            return index_;
        }

        /**
         * <code>uint32 index = 3;</code>
         *
         * @param value The index to set.
         * @return This builder for chaining.
         */
        public Builder setIndex(int value) {

            index_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>uint32 index = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIndex() {

            index_ = 0;
            onChanged();
            return this;
        }

        /**
         * <code>uint32 total = 4;</code>
         *
         * @return The total.
         */
        public int getTotal() {
            return total_;
        }

        /**
         * <code>uint32 total = 4;</code>
         *
         * @param value The total to set.
         * @return This builder for chaining.
         */
        public Builder setTotal(int value) {

            total_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>uint32 total = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTotal() {

            total_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MultiPart)
    }

}

