// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

public interface NothingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Nothing)
    com.google.protobuf.MessageOrBuilder {
}
