// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

/**
 * Protobuf type {@code Peers}
 */
public final class Peers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Peers)
    PeersOrBuilder {
    public static final int PEERS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:Peers)
    private static final org.tdf.sunflower.proto.Peers DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Peers>
        PARSER = new com.google.protobuf.AbstractParser<Peers>() {
        @java.lang.Override
        public Peers parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Peers(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new org.tdf.sunflower.proto.Peers();
    }

    private com.google.protobuf.LazyStringList peers_;
    private byte memoizedIsInitialized = -1;

    // Use Peers.newBuilder() to construct.
    private Peers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Peers() {
        peers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    private Peers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            peers_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        peers_.add(s);
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                peers_ = peers_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.tdf.sunflower.proto.Sunflower.internal_static_Peers_descriptor;
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.Peers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.Peers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static org.tdf.sunflower.proto.Peers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.tdf.sunflower.proto.Peers prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static org.tdf.sunflower.proto.Peers getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Peers> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
        return new Peers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.tdf.sunflower.proto.Sunflower.internal_static_Peers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tdf.sunflower.proto.Peers.class, org.tdf.sunflower.proto.Peers.Builder.class);
    }

    /**
     * <code>repeated string peers = 1;</code>
     *
     * @return A list containing the peers.
     */
    public com.google.protobuf.ProtocolStringList
    getPeersList() {
        return peers_;
    }

    /**
     * <code>repeated string peers = 1;</code>
     *
     * @return The count of peers.
     */
    public int getPeersCount() {
        return peers_.size();
    }

    /**
     * <code>repeated string peers = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The peers at the given index.
     */
    public java.lang.String getPeers(int index) {
        return peers_.get(index);
    }

    /**
     * <code>repeated string peers = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the peers at the given index.
     */
    public com.google.protobuf.ByteString
    getPeersBytes(int index) {
        return peers_.getByteString(index);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        for (int i = 0; i < peers_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, peers_.getRaw(i));
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < peers_.size(); i++) {
                dataSize += computeStringSizeNoTag(peers_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getPeersList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.tdf.sunflower.proto.Peers)) {
            return super.equals(obj);
        }
        org.tdf.sunflower.proto.Peers other = (org.tdf.sunflower.proto.Peers) obj;

        if (!getPeersList()
            .equals(other.getPeersList())) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getPeersCount() > 0) {
            hash = (37 * hash) + PEERS_FIELD_NUMBER;
            hash = (53 * hash) + getPeersList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peers> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.tdf.sunflower.proto.Peers getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code Peers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Peers)
        org.tdf.sunflower.proto.PeersOrBuilder {
        private int bitField0_;
        private com.google.protobuf.LazyStringList peers_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        // Construct using org.tdf.sunflower.proto.Peers.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_Peers_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_Peers_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    org.tdf.sunflower.proto.Peers.class, org.tdf.sunflower.proto.Peers.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            peers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.tdf.sunflower.proto.Sunflower.internal_static_Peers_descriptor;
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.Peers getDefaultInstanceForType() {
            return org.tdf.sunflower.proto.Peers.getDefaultInstance();
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.Peers build() {
            org.tdf.sunflower.proto.Peers result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.tdf.sunflower.proto.Peers buildPartial() {
            org.tdf.sunflower.proto.Peers result = new org.tdf.sunflower.proto.Peers(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) != 0)) {
                peers_ = peers_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.peers_ = peers_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.tdf.sunflower.proto.Peers) {
                return mergeFrom((org.tdf.sunflower.proto.Peers) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.tdf.sunflower.proto.Peers other) {
            if (other == org.tdf.sunflower.proto.Peers.getDefaultInstance()) return this;
            if (!other.peers_.isEmpty()) {
                if (peers_.isEmpty()) {
                    peers_ = other.peers_;
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    ensurePeersIsMutable();
                    peers_.addAll(other.peers_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            org.tdf.sunflower.proto.Peers parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.tdf.sunflower.proto.Peers) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private void ensurePeersIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                peers_ = new com.google.protobuf.LazyStringArrayList(peers_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @return A list containing the peers.
         */
        public com.google.protobuf.ProtocolStringList
        getPeersList() {
            return peers_.getUnmodifiableView();
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @return The count of peers.
         */
        public int getPeersCount() {
            return peers_.size();
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The peers at the given index.
         */
        public java.lang.String getPeers(int index) {
            return peers_.get(index);
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the peers at the given index.
         */
        public com.google.protobuf.ByteString
        getPeersBytes(int index) {
            return peers_.getByteString(index);
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The peers to set.
         * @return This builder for chaining.
         */
        public Builder setPeers(
            int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensurePeersIsMutable();
            peers_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param value The peers to add.
         * @return This builder for chaining.
         */
        public Builder addPeers(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensurePeersIsMutable();
            peers_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param values The peers to add.
         * @return This builder for chaining.
         */
        public Builder addAllPeers(
            java.lang.Iterable<java.lang.String> values) {
            ensurePeersIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, peers_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPeers() {
            peers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string peers = 1;</code>
         *
         * @param value The bytes of the peers to add.
         * @return This builder for chaining.
         */
        public Builder addPeersBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensurePeersIsMutable();
            peers_.add(value);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Peers)
    }

}

