// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunflower.proto

package org.tdf.sunflower.proto;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Pong)
    com.google.protobuf.MessageOrBuilder {
}
