# This is a basic workflow to help you get started with Actions

name: Jar
# This is a basic workflow to help you get started with Actions

on: [ workflow_dispatch]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 11
          # Java distribution. See the list of supported distributions in README file
          distribution: adopt
          cache: gradle
          
      - name: build
        run: |   
          chmod a+x ./gradlew
          ./gradlew bootJar
                     
           
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: sunflower-core/build/libs

        
          
               
     
